#include <iostream>
using namespace std;

typedef double Matrix[10][10];
typedef double Mat[10];

void generate(Matrix, int a);
void output(Matrix, int a);
void edit(Matrix, int a);

int main()
{
    Matrix A;
    int a;
    cout << "Enter matrix size: ";
    cin >> a;
    generate(A, a);
    cout << "\nAutogenerated matrix: " << endl;
    output(A, a);
    edit(A, a);
    cout << "\n\nEdited matrix: " << endl;
    output(A, a);
}

void generate(Matrix matr, int a)
{
    srand(time(NULL));
    for (int i = 0; i < a; i++)
    {
        for (int j = 0; j < a; j++)
        {
            matr[i][j] = (double)(-90 + rand() % 190) / 10;
        }
    }
}

void output(Matrix matr, int a)
{
    for (int i = 0; i < a; i++)
    {
        for (int j = 0; j < a; j++)
        {
            cout.width(6);
            cout << matr[i][j];
        }
        cout << endl;
    }
}

void edit(Matrix matr, int a)
{
    double temp;
    int k = 0;
    Mat A;
    cout << "\nMain diagonal: ";
    for (int j = 0; j < a; j++)
    {
        for (int i = 0; i < a; i++)
        {
            if (i == j)
            {
                A[k] = matr[j][i];
                k++;
            }
        }
        cout.width(6);
        cout << A[j];
    }

    cout << "\n\nSorted main diagonal: ";
    for (int i = 1; i < a; i++)
    {
        int j = i;
        while (j > 0 && A[j - 1] < A[j])
        {
            temp = A[j - 1];
            A[j - 1] = A[j];
            A[j] = temp;
            swap(matr[j - 1], matr[j]);
            j--;
        }
    }
    for (int i = 0; i < a; i++)
    {
        cout.width(6);
        cout << A[i];
    }
}